name: jet_dogue
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  go_router: ^10.0.0
  flutter_bloc: ^8.1.3
  phosphor_flutter: ^2.0.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  xml: ^6.3.0
  url_launcher: ^6.1.12
  video_player: ^2.7.0
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: false
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/competitions/
    - assets/images/teams/
    - assets/videos/
  fonts:
    - family: Termina
      fonts:
        - asset: assets/fonts/Termina/Termina-Regular.otf
        - asset: assets/fonts/Termina/Termina-Bold.otf
          weight: 700
        - asset: assets/fonts/Termina/Termina-Medium.otf
          weight: 500
