name: Main
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sdk
        id: sdk
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: version
        run: |
          flutter --version
          echo ${{ steps.sdk.outputs.ARCHITECTURE }}
          echo ${{ steps.sdk.outputs.CACHE-KEY }}
          echo ${{ steps.sdk.outputs.CHANNEL }}
          echo ${{ steps.sdk.outputs.VERSION }}
      - name: dependencies
        run: flutter pub get
      - name: build
        run: dart run build_runner build --delete-conflicting-outputs
      - name: format
        run: dart format . --set-exit-if-changed
      - name: analyze
        run: flutter analyze
